### ISSUE TITLE
Django 3.2 breaks django-fsm: get_available_FIELD_transitions is empty for abstract models with FSMField in Django 3.2

### ISSUE THREAD

**Issue by florianm** [viewflow/django-fsm#256]
Hi, first of all, thanks for this great package! I've been using it for all Django apps with approval/QA workflows for 9 years now and it's an absolute game-changer.

I've just noticed that after upgrading Django from 3.1 to 3.2, all django-fsm status transitions vanished. I read the code but didn't find any obvious breakage. There's no error message, the transitions simply don't show up. I can still execute the transition functions from the shell_plus.
Obviously I have to do way more homework before I can file a useful bug report here, but I wanted to share my findings and ask whether any other django-fsm users have run into the same issue.

* Django 3.2 with django-fsm is broken (no transitions). [requirements.txt](https://github.com/dbca-wa/wastd/blob/0b2e373027a19ef7d471ab489bf43181c8fbd743/requirements/base.txt) with obviously way too many dependencies for a MVE.
* Downgrade to Django 3.1 (leave everything else up to latest) works again. [requirements.txt](https://github.com/dbca-wa/wastd/blob/ee9c40401cc2adab1424b9b42444926ff7ab9e30/requirements/base.txt)

I had to fix a few minor things to upgrade to Django 3.2 (app config and a patch for django-grappelli). The downgrade to Django 3.1 worked without any changes to the upgrade fixes.

**Comment by pfcodes** [comment]
Any workarounds to this that don't include downgrading?

**Comment by felixmeziere** [comment]
yes, for example get_all_FIELD_transitions does not work anymore

**Comment by roniemartinez** [comment]
We've been trying to solve this issue for a few days and found out that an abstract base class causes the issue. Hope this helps finding the correct solution.

This breaks:

```python
class BlogPostMixin(models.Model):
    state = FSMKeyField(default='new')

    @transition(field=state, source='new', target='published')
    def publish(self):
        pass

    class Meta:
        abstract = True  # this probably causes the issue


class BlogPost(BlogPostMixin):
    ...

```

Moving the state and transitions to the main model works but there are plenty of code repetition if you are reusing the same state and transitions which a Mixin supposedly solves:

```python
class BlogPost(models.Model):
    state = FSMKeyField(default='new')

    @transition(field=state, source='new', target='published')
    def publish(self):
        pass
```

**Comment by florianm** [comment]
@roniemartinez thanks for the follow-up, this is exactly how I use django-fsm. I use abstract models as mixins to keep fsm logic DRY. I assume many others do the same.

**Comment by exister** [comment]
For anyone looking for a quick fix, I was able to make it work by overriding `django_fsm.FSMFieldMixin._collect_transitions`

```python
    def _collect_transitions(self, *args, **kwargs):
        """
        Fix for https://github.com/viewflow/django-fsm/issues/256
        """

        sender = kwargs["sender"]

        if not issubclass(sender, self.base_cls):
            return

        def is_field_transition_method(attr):
            return (
                (inspect.ismethod(attr) or inspect.isfunction(attr))
                and hasattr(attr, "_django_fsm")
                and attr._django_fsm.field.name == self.name
            )

        sender_transitions = {}
        transitions = inspect.getmembers(sender, predicate=is_field_transition_method)
        for method_name, method in transitions:
            method._django_fsm.field = self
            sender_transitions[method_name] = method

        self.transitions[sender] = sender_transitions
```

The only difference is `attr._django_fsm.field.name == self.name` vs `attr._django_fsm.field in [self, self.name]`.

**Comment by ticosax** [comment]
That's this commit that introduced the regression for django-fsm

https://github.com/django/django/commit/502e75f9ed5476ffe8229109acf0c23999d4b533

I'm afraid that none of the already proposed solution is the right fix. We need to treat inheritance of fields more explicitly.

**Comment by ticosax** [comment]
Could be that's maybe a regression in django itself. I posted a comment to ask for clarification.
https://code.djangoproject.com/ticket/31750#comment:4

**Comment by ticosax** [comment]
> Could be that's maybe a regression in django itself. I posted a comment to ask for clarification.
> https://code.djangoproject.com/ticket/31750#comment:4

They clarified it's by design. we will have to provide a fix for django-fsm.

**Comment by felixmeziere** [comment]
Any progress on this super dangerous issue? :/

**Comment by marine-mb** [comment]
Hi,
We also use many abstract classes with our transition to avoid duplication. We had to revert our Django update for the moment to wait for an update on this issue.
Do you have an idea about when it will be fixed? :)

**Comment by roniemartinez** [comment]
@marine-mb 

@ticosax [fix (open PR)](https://github.com/viewflow/django-fsm/pull/262) worked for us.

With several users depending on this project, maybe this is the time to add new maintainers to the project @kmmbvnr

**Comment by felixmeziere** [comment]
Did anyone try to work on this? 😞

**Comment by felixmeziere** [comment]
The fix of mentioned by @roniemartinez causes an issue when I run `runserver`, not sure if it's my setup or not.

**Comment by felixmeziere** [comment]
@roniemartinez got to the bottom of it: as the check `attr._django_fsm.field in [self, self.name]` shows, `attr._django_fsm.field` can sometimes be a string, in which case the check after raises my error.

The correct fix should therefore be (if you want to update the PR):

```python
from django.db.models import Field

    def is_field_transition_method(attr):
            return (inspect.ismethod(attr) or inspect.isfunction(attr)) \
                and hasattr(attr, '_django_fsm') \
                and (attr._django_fsm.field in [self, self.name]
                    or attr._django_fsm.field.creation_counter == self.creation_counter)
```

This is tested in production, should work. Thank you!

**Comment by roniemartinez** [comment]
@ticosax

**Comment by kmmbvnr** [comment]
@felixmeziere  thank you for the correct fix! I just released the new version.

I feel that the django-fsm became too complicated than it should be. And the core problem is the 11 years old design decision to combine fsm with Django model class

[Compositional approach](https://medium.com/swlh/implementing-finite-state-machine-as-python-language-native-construct-cb56e3c46215) with class separated fsm simplifies implementation in a many ways, and gives much more flexibility for abstract/base classes hierarchies

I think it was the last release of django-fsm 2.0 an the project reached end of life. The new django-fsm 3.0 ideas is available as [`viewflow.fsm` module](https://docs-next.viewflow.io/fsm/index.html) To simplify support, new features development, and quickle release cycles I'm moving all my projects into the single viewflow library.

Thank you folks for the help, over all those years!

**Comment by ticosax** [comment]
Still not fixed. https://github.com/viewflow/django-fsm/commit/910ce79cfef1b285ed8fd6e5d7727a98aac7bc1d#r59705075

**Comment by kmmbvnr** [comment]
I don't get into details deep, but current test behavior is consistent between Django versions and previous django-fsm implementation

For better support of fsm inheritance, please consider to switch to viewflow.fsm, that don't have such issues by design.

**Comment by hbast** [comment]
I would like to reopen this Issue. There is a patch and a merge request for this issue. May I ask why this is not included?

I have seen the reference to `viewport`. If I need something like a state machine for Django this library (django-fsm) is the first place to go due to its maturity, size, prominence and communiy. The outward appearance of `viewport` doesn`t let me understand what BPMN has to do with a state machine implementation for Django. I could not find any documentation on how to use `viewport` as a lightweight successor for `django-fsm`. As a developer I refuse a bit to include a big (external) library of which I only want to use a supporting module.

I ask to reconsider the decision to drop `django-fsm` just like that, especially since the way to the successor doesn`t seem to be really known.

**Comment by ticosax** [comment]
@hbast I'm just an external contributor, who love and rely on django-fsm. 
I don't have any kind of influence on these decisions. I can just say that, if it were to change, I'm interested to take some responsibilities to maintain this project if that would help.

**Comment by roniemartinez** [comment]
I would love it if the owner transfers this project to the community.
